# DEV ENVIRONMENT

services:
  # NADIS web
  nadis-web:
    build:
      context: .
      dockerfile: web/Dockerfile.ibe.dev
    ports:
      - "5173:5173"
    volumes:
      - ./web/:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
